import { StyleSheet } from "react-native";
import { Colors } from "./shared";

export default (c: Colors) =>
  StyleSheet.create({
    // right-click context menu
    menu: {
      position: "fixed" as any,
      minWidth: 200,
      backgroundColor: c.bgCard,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.border,
      paddingVertical: 4,
      zIndex: 10000,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.2,
      shadowRadius: 16,
    },
    menuItem: { paddingVertical: 10, paddingHorizontal: 14 },
    menuItemText: { color: c.textPrimary, fontSize: 14 },
    menuHint: { color: c.textMuted, fontSize: 12, fontStyle: "italic" },

    // modal
    overlay: {
      position: "fixed" as any,
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0,0,0,0.4)",
      alignItems: "center",
      justifyContent: "center",
      zIndex: 10001,
    },
    modal: {
      width: 460,
      maxWidth: "90%",
      backgroundColor: c.bgCard,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      padding: 24,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.25,
      shadowRadius: 24,
    },
    modalTitle: { color: c.textPrimary, fontSize: 18, fontWeight: "800", marginBottom: 16 },
    label: { color: c.textSecondary, fontSize: 13, fontWeight: "600", marginTop: 12, marginBottom: 6 },
    input: {
      backgroundColor: c.bg,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 12,
      color: c.textPrimary,
      fontSize: 14,
    },
    textarea: {
      backgroundColor: c.bg,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 12,
      color: c.textPrimary,
      fontSize: 14,
      minHeight: 120,
      textAlignVertical: "top",
    },
    hint: { color: c.textMuted, fontSize: 12, marginTop: 6 },

    // [[ concept-reference autocomplete
    suggestWrap: { position: "relative" },
    suggestBox: {
      position: "absolute",
      top: "100%",
      left: 0,
      right: 0,
      marginTop: 2,
      backgroundColor: c.bgCard,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 8,
      paddingVertical: 4,
      zIndex: 10002,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.2,
      shadowRadius: 14,
    },
    suggestItem: { paddingVertical: 8, paddingHorizontal: 12 },
    suggestName: { color: c.textPrimary, fontSize: 14, fontWeight: "600" },
    suggestId: { color: c.textMuted, fontSize: 12 },
    suggestEmpty: { paddingVertical: 8, paddingHorizontal: 12 },
    suggestNew: { color: c.accentText, fontSize: 13, fontStyle: "italic" },

    actions: { flexDirection: "row", justifyContent: "flex-end", gap: 10, marginTop: 24 },
    btn: { paddingVertical: 10, paddingHorizontal: 18, borderRadius: 8 },
    btnCancel: { backgroundColor: c.bg, borderWidth: 1, borderColor: c.border },
    btnCancelText: { color: c.textSecondary, fontSize: 14, fontWeight: "600" },
    btnSave: { backgroundColor: c.accent },
    btnSaveText: { color: "#fff", fontSize: 14, fontWeight: "700" },
    error: { color: "#ef4444", fontSize: 13, marginTop: 10 },
  });
